### ISSUE TITLE
[tests] wrong local version of Cairo used?

### ISSUE THREAD

**Issue by ctrlcctrlv** [BlackFoundryCom/black-renderer#71]
Leading to bad output on some tests if mismatch.

Thus, why [`f3ec4ff`](https://github.com/BlackFoundryCom/black-renderer/commit/f3ec4ff9e8cedb8952a2b50c508ec328693628ae#diff-68b9dff6f11325f1a9519b88aca69acf1a2ae12f5d75aa1bcdae0138d0530917) included a :tumbler_glass: PDF while https://github.com/BlackFoundryCom/black-renderer/commit/1d22b44605cfb62b83e33113febd46e6f663d12b did not.

**Comment by justvanrossum** [comment]
I don't understand what happened that caused your test failure, nor what you did to fix it.

**Comment by ctrlcctrlv** [comment]
```diff
# pdftk vector_noto_u1F943_cairo.pdf output noto.ps uncompress
# git diff --no-index noto.ps /tmp/noto.ps
diff --git a/noto.ps b/tmp/noto.ps
index 30f658c..2faaf46 100644
--- a/noto.ps
+++ b/tmp/noto.ps
@@ -358,8 +358,8 @@ endobj
 13 0 obj
 
 <<
-/CreationDate (D:20211101182647+01'00)
-/Producer (cairo 1.16.0 \(https://cairographics.org\))
+/CreationDate (D:20220204234134-05'00)
+/Producer (cairo 1.17.4 \(https://cairographics.org\))
 >>
 endobj
 xref
```

**Comment by justvanrossum** [comment]
But: I see no changes in the test code (except a cosmetic change to an assert) and no changes to the test data. So any failure seems to be caused by other changes in your PR.

The CI otherwise doesn't fail, see eg. today's pyup PR run: https://github.com/BlackFoundryCom/black-renderer/actions/runs/1806943448

**Comment by ctrlcctrlv** [comment]
What?

https://github.com/BlackFoundryCom/black-renderer/commit/f3ec4ff9e8cedb8952a2b50c508ec328693628ae changes [Tests/expectedOutput/vector_noto_u1F943_cairo.pdf](https://github.com/BlackFoundryCom/black-renderer/commit/f3ec4ff9e8cedb8952a2b50c508ec328693628ae#diff-68b9dff6f11325f1a9519b88aca69acf1a2ae12f5d75aa1bcdae0138d0530917)

https://github.com/BlackFoundryCom/black-renderer/commit/1d22b44605cfb62b83e33113febd46e6f663d12b does not.

**Comment by justvanrossum** [comment]
Yet the former failed while the latter did not.

I now think I understand what happened:
- the expected images in the repo are made with the same Cairo as what runs on the CI
- you have a different Cairo running locally, so your local tests failed
- you fixed your local test failure, but this broke the CI

The fix is to ignore the Cairo version number that's written in the PDF. I will implement this now.
