### ISSUE TITLE
PaintTranslate inside PaintGlyph transforms the parent PaintGlyph, not its contents

### ISSUE THREAD

**Issue by RobertPratley** [BlackFoundryCom/black-renderer#93]
When a PaintGlyph contains a PaintTranslate, the transformation described by the PaintTranslate is getting applied to the parent PaintGlyph, instead of paints supplied to the PaintTranslate.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/22640107/172857196-cc2b1e33-a718-468c-b03e-bbb23389f415.png">

**Comment by anthrotype** [comment]
maybe you could attache the test font as well, as well as the text for activating that glyph

**Comment by justvanrossum** [comment]
Seems there's also a difference in shape. But yes, a test font would be great.

**Comment by RobertPratley** [comment]
Of course, thanks both. Test font attached, with the glyph in the screenshot above accessible in 'A'
[BlackRenderer_paintTransformTest.zip](https://github.com/BlackFoundryCom/black-renderer/files/8871276/BlackRenderer_paintTransformTest.zip)

**Comment by justvanrossum** [comment]
I think I've found the problem and a fix.

Would you allow me to add this font to the test suite data?

I would have to make a change, because I think the bounding box for the `A` glyph is now taken from the black-and-white glyph, which is too small for the color glyph. This shows when using the blackrenderer command line tool. (FontGoggles so far ignores the glyph bounds, if I remember correctly.)

**Comment by RobertPratley** [comment]
Hi Just, of course - if it's helpful please add it

**Comment by justvanrossum** [comment]
And there was much rejoicing.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/4246121/172937234-910b22eb-b428-4757-9ade-b775c32015fc.png">

https://github.com/justvanrossum/fontgoggles/releases/tag/v1.4.5

Thanks for reporting!
